apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: techtrends
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
  type: ClusterIP