namespace:
  name: prod 

image:
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"
 
service:
  port: 7111